version: '3.7'
services:

  app:
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s      
      resources:
        limits:
          memory: 4096M
  nginx:
    ports:
      - "${PROD_NGINX_HOST_HTTP_PORT}:80"
      - "${PROD_NGINX_HOST_HTTPS_PORT}:443"
    volumes:      
      - "${DOCKER_CONFIG_PATH}/nginx/conf-prod:/etc/nginx/conf.d"
      - "${DOCKER_CONFIG_PATH}/certbot/conf:/etc/letsencrypt"
      - "${DOCKER_CONFIG_PATH}/certbot/www:/var/www/certbot"
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s      

  node:
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s      

  mysql:
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s      
       
  supervisor:
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s  
      resources:
        limits:
          memory: 4096M
        
  certbot:
    container_name: ${PROJECT_ID}_certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - "${DOCKER_CONFIG_PATH}/certbot/conf:/etc/letsencrypt"
      - "${DOCKER_CONFIG_PATH}/certbot/www:/var/www/certbot"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s      
