version: '3.7'
services:

  app:
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s      

  nginx:
    ports:
      - "${DEV_NGINX_HOST_HTTP_PORT}:80"      
      - "${DEV_NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - "${DOCKER_CONFIG_PATH}/nginx/conf-dev:/etc/nginx/conf.d"
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s      

  node:
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s      

  mysql:
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s      
       
  supervisor:
    deploy:
      restart_policy:
        condition: any 
        delay: 5s
        max_attempts: 3
        window: 120s  