version: '3.7'
services:

  app:
    container_name: ${PROJECT_ID}_app
    build: 
      context: ${DOCKER_CONFIG_PATH}/app
      args:
        - "PHP_FPM_VERSION:${PHP_FPM_VERSION}"
        - "COMPOSER_VERSION:${COMPOSER_VERSION}"
    environment:
      PROJECT_ID : ${PROJECT_ID}
      DOCKER_PHP_CONFIG : ${DOCKER_PHP_CONFIG}
      DOCKER_XDEBUG : ${DOCKER_XDEBUG}
      DOCKER_XDEBUG_PORT : ${DOCKER_XDEBUG_PORT}
    depends_on:
     - mysql
    volumes:
      - "${HOST_DOCUMENT_ROOT}:${NGINX_DOCUMENT_ROOT}/${PROJECT_ID}"
    
  nginx:
    container_name: ${PROJECT_ID}_nginx
    image: nginx:1.16-alpine    
    depends_on:
      - app
    ports:
      - "${LOCAL_NGINX_HOST_HTTP_PORT}:80"      
    volumes:
      - "${HOST_DOCUMENT_ROOT}:${NGINX_DOCUMENT_ROOT}/${PROJECT_ID}"
      - "${DOCKER_CONFIG_PATH}/nginx/conf-dev:/etc/nginx/conf.d"
    
  node:
    container_name: ${PROJECT_ID}_node
    build: 
      context: ${DOCKER_CONFIG_PATH}/node
      args:
        - NODE_VERSION=${NODE_VERSION}
    depends_on:
      - app
    volumes:
      - "${HOST_DOCUMENT_ROOT}:${NGINX_DOCUMENT_ROOT}/${PROJECT_ID}"

  mysql:
    container_name: ${PROJECT_ID}_mysql
    build: 
      context: ${DOCKER_CONFIG_PATH}/mysql
      args:
        - "MYSQL_VERSION=${MYSQL_VERSION}"
    environment:
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "SERVICE_NAME=mysql"
    restart: unless-stopped
    tty: true 
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    volumes:
      - "${HOST_DATABASE_PATH}:/var/lib/mysql"    
      - "${DOCKER_CONFIG_PATH}/mysql/initdb:/docker-entrypoint-initdb.d"
       
  supervisor:
    container_name: ${PROJECT_ID}_supervisor
    build: 
      context: ${DOCKER_CONFIG_PATH}/supervisor 
      args:
        - PHP_VERSION=${PHP_FPM_VERSION}
    depends_on:
      - app 
    volumes:
      - "${HOST_DOCUMENT_ROOT}:${NGINX_DOCUMENT_ROOT}/${PROJECT_ID}"
      - "${DOCKER_CONFIG_PATH}/supervisor/supervisord.d:/etc/supervisord.d"   
      - "${DOCKER_CONFIG_PATH}/supervisor/logs:/var/log/supervisor"
